### ISSUE TITLE
Developer Commons wiki

### ISSUE THREAD

**Issue by ion-oset** [ion-oset/developer-commons#19]
### Tasks

- [x] Home Page
  - [x] Conventions for using the wiki
  - [x] Workflow for using the wiki
- [ ] Templates for kinds of pages
  - [ ] Best practices
  - [ ] Style guides
  - [ ] Toolchains / language ecosystems
