### ISSUE TITLE
Developer Commons discussion forum

### ISSUE THREAD

**Issue by ion-oset** [ion-oset/developer-commons#20]
### Tasks

- [x] Research how [GitHub Discussions](https://docs.github.com/en/discussions) work. See [About Discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions).
- [x] Choose and create discussion categories
- [ ] Choose and create discussion labels
   Note that they apply across the repository not just discussions.
